language: java
deploy:
  provider: heroku
  app: cricketauctionapp
  api_key:
    secure: "eae0ec9c-9351-41c6-98a8-1f79d584e74c"
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install
